<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="fc3c13788461" failures="0" tests="28" name="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" time="0.156" errors="0" timestamp="25 Oct 2021 16:10:12 GMT" skipped="0">
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableErrorUsingException" time="0.001"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.002"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testBackoff" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testExponentialBackoffDelayRequired" time="0.006"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.001"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableErrorUsingException" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.109"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableErrorUsingException" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableErrorUsingException" time="0.025"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableErrorUsingException" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.001"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableErrorUsingException" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.009"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableErrorUsingException" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableErrorUsingException" time="0.001"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.001"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableErrorUsingException" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableErrorUsingException" time="0.000"/>
  <testcase classname="org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest" name="testIsRecoverableError" time="0.000"/>
</testsuite> <!-- org.artifactory.addon.replication.core.push.error.ReplicationErrorUtilTest -->
